<?php

/**
 * Implements hook_preprocess_html().
 * Sets the primary color
 * @param [type] $variables
 * @return void
 */
function claro_overrides_preprocess_html(&$variables) {
  $current_theme = \Drupal::theme()->getActiveTheme()->getName();
  if ($current_theme === 'claro') {
    $primaryColor = 'blue';
    $moduleHandler = \Drupal::service('module_handler');
    if ($moduleHandler->moduleExists('contact')) {
      $config = \Drupal::config('custom_company_token.settings');
      $primaryColor = $config->get('color');
    };

    $style = [
      '#tag' => 'style',
      '#value' => ":root {\n --primary: ".$primaryColor.";\n}",
    ];
    $variables['page']['#attached']['html_head'][] = [$style, 'claro-overrides'];
  }
}

/**
 * Implements hook_page_attachments().
 *
 * @param array $attachments
 */
function claro_overrides_page_attachments(array &$attachments) {
  $current_theme = \Drupal::theme()->getActiveTheme()->getName();
  if ($current_theme === 'claro') {
    $attachments['#attached']['library'][] = 'claro_overrides/claro_overrides';
  }
}

function claro_overrides_preprocess_paragraph(&$variables) {
  // Get the paragraph entity.
  $paragraph = $variables['paragraph'];

  // Check if it has the 'field_paragraph_styles' field.
  if ($paragraph->hasField('field_paragraph_styles')) {
    // Get the value of the 'field_paragraph_styles' field and set it as a class on the paragraph.
    $styles = $paragraph->get('field_paragraph_styles')->getValue();
    if (!empty($styles)) {
      foreach ($styles as $style) {
        $variables['attributes']['class'][] = $style['value'];
/*         if (str_contains($style['value'],'b-') || str_contains($style['value'],'bg-')) {
          $variables['attributes']['class'][] = 'padding';
        } */
      }
    }
  }
  // Check if it has the 'field_paragraph_text_styles' field.
  if ($paragraph->hasField('field_paragraph_text_styles')) {
    // Get the value of the 'field_paragraph_styles' field and set it as a class on the paragraph.
    $textstyles = $paragraph->get('field_paragraph_text_styles')->getValue();
    if (!empty($textstyles)) {
      foreach ($textstyles as $style) {
        $variables['attributes']['class'][] = $style['value'];
      }
    }
  }
  // Check if it has the 'field_paragraph_css' field.
  if ($paragraph->hasField('field_paragraph_css')) {
    $css_class = $paragraph->get('field_paragraph_css')->value;
    $variables['attributes']['class'][] = $css_class;
  }


}


